name: flutterfireabsetest
version: 1.0.0+1
publish_to: none
description: a flutter test project
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^8.0.0
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  firebase_remote_config: ^4.2.6
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  firebase_auth: ^4.10.0
  google_mobile_ads: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  assets_gen: ^1.4.1

flutter:
  uses-material-design: true

import_sorter:
  emojis: true
  comments: true
